devsearch/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('projects/',include('projects.urls')),
    path('',include('users.urls')),
]
urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from . import views

urlpatterns=[
    path('login/',views.loginPage,name='login'),
    path('logout/',views.logoutUser,name='logout'),
    path('register/',views.registerUser,name='register'),
    
    path('',views.profiles,name='profiles'),
    path('profile/<str:pk>/',views.userProfile,name='user_profile'),
    path('account/',views.userAccount,name='user_account'),
    path('update-account/',views.editAccount,name='edit_account'),

]

projects/models.py
from email.policy import default
from random import choices
from django.db import models
from users.models import Profile
import uuid
# Create your models here.
class project(models.Model):
    owner=models.ForeignKey(Profile,null=True,blank=True,on_delete=models.SET_NULL)
    title=models.CharField(max_length=200)
    description=models.TextField(null=True,blank=True)
    featured_image=models.ImageField(null=True,blank=True,default='default.jpg')
    demo_link=models.CharField(max_length=2000,null=True,blank=True)
    source_link=models.CharField(max_length=2000,null=True,blank=True)
    tags=models.ManyToManyField('Tag',blank=True)
    vote_total=models.IntegerField(default=0,null=True,blank=True)
    vote_ratio=models.IntegerField(default=0,null=True,blank=True)
    created=models.DateTimeField(auto_now_add=True)
    id=models.UUIDField(default=uuid.uuid4,unique=True,primary_key=True,editable=False)
    def __str__(self):
        return self.title

class Review(models.Model):
    #owner
    project=models.ForeignKey(project,on_delete=models.CASCADE)
    VOTE_TYPE=(('up','Up Vote'),('down','Down vote'))
    body=models.TextField(null=True,blank=True)
    value=models.CharField(max_length=200,choices=VOTE_TYPE)
    id=models.UUIDField(default=uuid.uuid4,unique=True,primary_key=True,editable=False)
    def __str__(self):
        return self.value

class Tag(models.Model):
    name=models.CharField(max_length=200)
    created=models.DateTimeField(auto_now_add=True)
    id=models.UUIDField(default=uuid.uuid4,unique=True,primary_key=True,editable=False)
    def __str__(self):
        return self.name

users/models.py
from email.policy import default
from venv import create
from django.db import models
from django.contrib.auth.models import User
import uuid

# Create your models here.
class Profile(models.Model):
    user=models.OneToOneField(User,on_delete=models.CASCADE,null=True,blank=True)
    name=models.CharField(max_length=200,blank=True,null=True)
    user_name=models.CharField(max_length=200,blank=True,null=True)
    location=models.CharField(max_length=200,blank=True,null=True)
    email=models.EmailField(max_length=500,blank=True,null=True)
    short_intro=models.CharField(max_length=200,blank=True,null=True)
    bio=models.TextField(blank=True,null=True)
    profile_image=models.ImageField(blank=True,null=True,upload_to='profiles/',default='profiles/user-default.png')
    social_github=models.CharField(max_length=200,blank=True,null=True)
    social_twitter=models.CharField(max_length=200,blank=True,null=True)
    social_linkedin=models.CharField(max_length=200,blank=True,null=True)
    social_youtube=models.CharField(max_length=200,blank=True,null=True)
    social_website=models.CharField(max_length=200,blank=True,null=True)
    created=models.DateTimeField(auto_now_add=True)
    id=models.UUIDField(default=uuid.uuid4,unique=True,primary_key=True,editable=False)

    def __str__(self):
        return str(self.user_name)

class Skill(models.Model):
    owner=models.ForeignKey(Profile,null=True,blank=True,on_delete=models.CASCADE)
    name=models.CharField(max_length=200,blank=True,null=True)
    description=models.TextField(blank=True,null=True)
    created=models.DateTimeField(auto_now_add=True)
    id=models.UUIDField(default=uuid.uuid4,unique=True,primary_key=True,editable=False)

    def __str__(self):
        return str(self.name)

users/forms.py
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from users.models import Profile

class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model=User
        fields=['first_name','email','username','password1','password2']
        labels={'first_name':'Name',}
    def __init__(self,*args,**kwargs):
        super(CustomUserCreationForm,self).__init__(*args,**kwargs)
        for name,field in self.fields.items():
            field.widget.attrs.update({'class':'input'})

class ProfileForm(ModelForm):
    class Meta:
        model=Profile
        fields=['user_name','name','email','short_intro','bio',
        'profile_image','social_github','social_linkedin','social_website','social_youtube']
    def __init__(self,*args,**kwargs):
        super(ProfileForm,self).__init__(*args,**kwargs)
        for name,field in self.fields.items():
            field.widget.attrs.update({'class':'input'})

users/views.py
import profile
from django.shortcuts import render,redirect
from .models import Profile
from django.contrib import messages
from django.contrib.auth import login,authenticate,logout
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from users.forms import CustomUserCreationForm,ProfileForm
# Create your views here.
def profiles(request):
    all_profiles=Profile.objects.all()
    print(all_profiles)
    context={'profiles':all_profiles}
    return render(request,'users/profiles.html',context)

def userProfile(request,pk):
    u_profile=Profile.objects.get(id=pk)
    topSkills=u_profile.skill_set.exclude(description__exact="")
    otherSkills=u_profile.skill_set.filter(description="")
    context={'profile':u_profile,'topSkills':topSkills,'otherSkills':otherSkills}
    return render(request,'users/user-profile.html',context)

def loginPage(request):
    
   
    if request.user.is_authenticated:
        return redirect('profiles') 
    if request.method=='POST':
        username=request.POST['username']
        password=request.POST['password']
        try:
            user=User.objects.get(username=username)
        except:
            messages.error(request,"Username does not exist")
        user=authenticate(request,username=username,password=password)
        if user is not None:
            login(request,user)
            return redirect('profiles')
        else:
            messages.error(request,'Username or password incorrect')
        print(request.POST)
    return render(request,"users/login_register.html")

def logoutUser(request):
    logout(request)
    messages.success(request,'Logged out Succesfully')
    return redirect('login')

def registerUser(request):
    page='register'
    form=CustomUserCreationForm()
    if request.method=="POST":
        form=CustomUserCreationForm(request.POST)
        if form.is_valid():
            print('somehow passed form validation')
            user1=form.save(commit=False)
            user1.username=user1.username.lower()
            user1.save()
            print("saved")
            messages.success(request,"Your account has been created!")
            login(request,user1)
            return redirect('user_account')
        else:
            messages.error(request,"someting wong!")
            context={'page':page,'form':form}
            return render(request,'users/login_register.html',context)
            
    context={'page':page,'form':form}
    return render(request,'users/login_register.html',context)

@login_required(login_url='login')
def userAccount(request):
    profile=request.user.profile
    topSkills=profile.skill_set.exclude(description__exact="")
    context={'profile':profile,'topSkills':topSkills}
    return render(request,'users/account.html',context)

@login_required(login_url='login')
def editAccount(request):
    profile=request.user.profile
    form=ProfileForm(instance=profile)
    if request.method=="POST":
        form=ProfileForm(request.POST,request.FILES,instance=profile)
        if form.is_valid():
            form.save()
            return redirect('user_account')

    
    context={'form':form}
    return render(request,'users/profile_form.html',context)

users/templates/users/account.html
{% extends 'main.html' %}
{% load static %}
{% block content %}
 <!-- Main Section -->
  <main class="settingsPage profile my-md">
    <div class="container">
      <div class="layout">
        <div class="column column--1of3">
          <div class="card text-center">
            <div class="card__body dev">
              <a class="tag tag--pill tag--main settings__btn" href="{% url 'edit_account' %}"><i class="im im-edit"></i> Edit</a>
              <img class="avatar avatar--xl dev__avatar" src="{{profile.profile_image.url}}" />
              <h2 class="dev__name">{{profile.name}}</h2>
              <p class="dev__title">{{profile.short_intro}}</p>
              <p class="dev__location">{{profile.location}}</p>
              <ul class="dev__social">
                {% if profile.social_github %}
                <li>
                  <a title="Github" href="{{profile.social_github}}" target="_blank"><i class="im im-github"></i></a>
                </li>
                 {% endif %}
               {% if profile.social_twitter %}
                <li>
                  <a title="Twitter" href="{{profile.social_twitter}}" target="_blank"><i class="im im-twitter"></i></a>
                </li>
                {% endif %}
                {% if profile.social_linkedin %}
                <li>
                  <a title="LinkedIn" href="{{profile.social_linkedin}}" target="_blank"><i class="im im-linkedin"></i></a>
                </li>
                {% endif %}
                {% if profile.social_website %}
                <li>
                  <a title="Personal Website" href="{{profile.social_website}}" target="_blank"><i class="im im-globe"></i></a>
                </li>
                {% endif %}
              </ul>
              <a href="#" class="btn btn--sub btn--lg">Send Message </a>
            </div>
          </div>
        </div>
        <div class="column column--2of3">
          <div class="devInfo">
            <h3 class="devInfo__title">About Me</h3>
            <p class="devInfo__about">
              {{profile.bio}}
            </p>
          </div>
          <div class="settings">
            <h3 class="settings__title">Skills</h3>
            <a class="tag tag--pill tag--sub settings__btn tag--lg" href="#"><i class="im im-plus"></i> Add Skill</a>
          </div>

          <table class="settings__table">
           
             {% for skill in topSkills %}
               <tr>
              <td class="settings__tableInfo">
                <h4>{{skill.name}}</h4>
                <p>
                  {{skill.description}}
                </p>
              </td>
              <td class="settings__tableActions">
                <a class="tag tag--pill tag--main settings__btn" href="#"><i class="im im-edit"></i> Edit</a>
                <a class="tag tag--pill tag--main settings__btn" href="#"><i class="im im-x-mark-circle-o"></i>
                  Delete</a>
              </td>
            </tr>
              {% endfor %}
          </table>

          <div class="settings">
            <h3 class="settings__title">Projects</h3>
            <a class="tag tag--pill tag--sub settings__btn tag--lg" href="#"><i class="im im-plus"></i> Add Project</a>
          </div>

          <table class="settings__table">
            
            {% for project in profile.project_set.all %}
              
              <tr>
                <td class="settings__thumbnail">
                  <a href="{% url 'project' project.id %}"><img src="{{project.featured_image.url}}" alt="Project Thumbnail" /></a>
                </td>
                <td class="settings__tableInfo">
                  <a href="{% url 'project' project.id %}">{{project}}</a>
                  <p>
                    {{project.description|slice:"200"}}
                  </p>
                </td>
                <td class="settings__tableActions">
                  <a class="tag tag--pill tag--main settings__btn" href="#"><i class="im im-edit"></i> Edit</a>
                  <a class="tag tag--pill tag--main settings__btn" href="#"><i class="im im-x-mark-circle-o"></i>
                    Delete</a>
                </td>
              </tr>
             {% endfor %}
          </table>
        </div>
      </div>
    </div>
  </main>


{% endblock content %}

users/templates/users/form-template.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <!-- Favicon -->
    <link rel="shortcut icon" href="images/favicon.ico" type="image/x-icon" />
    <!-- Icon - IconMonster -->
    <link rel="stylesheet" href="https://cdn.iconmonstr.com/1.3.0/css/iconmonstr-iconic-font.min.css" />
    <!-- Mumble UI -->
    <link rel="stylesheet" href="uikit/styles/uikit.css" />
    <!-- Dev Search UI -->
    <link rel="stylesheet" href="styles/app.css" />

    <title>DevSearch - Connect with Developers!</title>
</head>

<body>
    <!-- Header Section -->
    <header class="header">
        <div class="container container--narrow">
            <a href="/" class="header__logo">
                <img src="images/logo.svg" alt="DevSearch Logo" />
            </a>
            <nav class="header__nav">
                <input type="checkbox" id="responsive-menu" />
                <label for="responsive-menu" class="toggle-menu">
                    <span>Menu</span>
                    <div class="toggle-menu__lines"></div>
                </label>
                <ul class="header__menu">
                    <li class="header__menuItem"><a href="index.html">Developers</a></li>
                    <li class="header__menuItem"><a href="projects.html">Projects</a></li>
                    <li class="header__menuItem"><a href="inbox.html">Inbox</a></li>
                    <li class="header__menuItem"><a href="account.html">My Account</a></li>
                    <li class="header__menuItem"><a href="login.html" class="btn btn--sub">Login/Sign Up</a></li>
                </ul>
            </nav>
        </div>
    </header>

    <!-- Main Section -->
    <main class="formPage my-xl">
        <div class="content-box">
            <div class="formWrapper">
                <a class="backButton" href="#"><i class="im im-angle-left"></i></a>
                <br>

                <form class="form" method="POST">
                    <!-- Input:Text -->
                    <div class="form__field">
                        <label for="formInput#text">Text Field: </label>
                        <input class="input input--text" id="formInput#text" type="text" name="text"
                            placeholder="Enter text" />
                    </div>

                    <!-- Input:Text -->
                    <div class="form__field">
                        <label for="formInput#text">Text Field: </label>
                        <input class="input input--text" id="formInput#text" type="text" name="text"
                            placeholder="Enter text" />
                    </div>

                    <!-- Input:Text -->
                    <div class="form__field">
                        <label for="formInput#text">Text Field: </label>
                        <input class="input input--text" id="formInput#text" type="text" name="text"
                            placeholder="Enter text" />
                    </div>
                    <input class="btn btn--sub btn--lg  my-md" type="submit" value="Submit" />
                </form>
            </div>
        </div>
    </main>
</body>

</html>

users/templates/users/login_register.html
{% extends "main.html" %}
{% load static %}
{% block content %}

{% if page == 'register' %}
    <div class="auth">
      <div class="card">
        <div class="auth__header text-center">
          <a href="/">
            <img src="{% static 'images/icon.svg' %}" alt="icon" />
          </a>
          <h3>Account SignUp</h3>
          <p>Create a new developer account</p>
        </div>

        <form method="POST" action="{% url 'register' %}" class="form auth__form">
         {% csrf_token %}
         {% for field in form %}
          <!-- Input:Text -->
          <div class="form__field">
            <label for="formInput#text">{{field.label}}</label>
            {{field}}
            {% for error in field.errors %}
            <p style="color:red;">{{error}}</p>
            {% endfor %}
          </div>

          {% endfor %}
          <div class="auth__actions">
            <input class="btn btn--sub btn--lg" type="submit" value="Sign  Up" />
          </div>
        </form>
        <div class="auth__alternative">
          <p>Already have an Account?</p>
          <a href="{% url 'login' %}">Log In</a>
        </div>
      </div>
    </div>

{% else %}
 <div class="auth">
      <div class="card">
        <div class="auth__header text-center">
          <a href="/">
            <img src="{% static 'images/icon.svg' %}" alt="icon" />
          </a>
          <h3>Account Login</h3>
          <p>Hello Developer, Welcome Back!</p>
        </div>

        <form action="{% url 'login' %}" class="form auth__form"  method="POST">
         {% csrf_token %}
          <!-- Input:Email -->
          <div class="form__field">
            <label for="formInput#text">Username: </label>
            <input
              class="input input--text"
              id="formInput#text"
              type="text"
              name="username"
              placeholder="Enter your username..."
            />
          </div>

          <!-- Input:Password -->
          <div class="form__field">
            <label for="formInput#password">Password: </label>
            <input
              class="input input--password"
              id="formInput#passowrd"
              type="password"
              name="password"
              placeholder="••••••••"
            />
          </div>
          <div class="auth__actions">
            <input class="btn btn--sub btn--lg" type="submit" value="Log In" />
            <a href="forgetpassword.html">Forget Password?</a>
          </div>
        </form>
        <div class="auth__alternative">
          <p>Don’t have an Account?</p>
          <a href="{% url 'register' %}">Sign Up</a>
        </div>
      </div>
    </div>
{% endif %}
{% endblock content %}

users/templates/users/profile_form.html
{% extends 'main.html' %}

{% block content %}

    
    
    <!-- Main Section -->
    <main class="formPage my-xl">
        <div class="content-box">
            <div class="formWrapper">
                <a class="backButton" href="{% url 'user_account' %}"><i class="im im-angle-left"></i></a>
                <br>

                <form method="POST" action="{% url 'edit_account' %}" enctype="multipart/form-data">
                    {% csrf_token %}
                    {% for field in form %}
                    <!-- Input:Text -->
                    <div class="form__field">
                        <label for="formInput#text">{{field.label}}</label>
                        {{field}}
                    </div>

                   {% endfor %}
                    <input class="btn btn--sub btn--lg  my-md" type="submit" value="Submit" />
                </form>
            </div>
        </div>
    </main>
{% endblock content %}

users/templates/users/profiles.html
{% extends 'main.html' %}
{% block content %}
<!-- Main Section -->
  <main class="home">
    <section class="hero-section text-center">
      <div class="container container--narrow">
        <div class="hero-section__box">
          <h2>CONNECT WITH <span>DEVELOPERS</span></h2>
          <h2>FROM AROUND THE WORLD</h2>
        </div>
        <div class="hero-section__search">
          <form class="form" action="#" method="get">
            <div class="form__field">
              <label for="formInput#search">Search Developers </label>
              <input class="input input--text" id="formInput#search" type="text" name="text"
                placeholder="Search by developer name" />
            </div>

            <input class="btn btn--sub btn--lg" type="submit" value="Search" />
          </form>
        </div>
      </div>
    </section>
    <!-- Search Result: DevList -->
    <section class="devlist">
      <div class="container">
        <div class="grid grid--three">
        {% for profile in profiles %}
          <div class="column card">
            <div class="dev">
              <a href="{% url 'user_profile' profile.id %}" class="card__body">
                <div class="dev__profile">
                  <img class="avatar avatar--md" src={{profile.profile_image.url}} alt="image" />
                  <div class="dev__meta">
                    <h3>{{profile.name}}</h3>
                    <h5>{{profile.short_intro}}</h5>
                  </div>
                </div>
                <p class="dev__info">
                  {{profile.bio|slice:"150"}}
                </p>
                <div class="dev__skills">
                {% for skill in profile.skill_set.all %}
                  <span class="tag tag--pill tag--main">
                    <small>{{skill}}</small>
                  </span>
                {% endfor %}
                </div>
              </a>
            </div>
            
          </div>
          {% endfor %}
          </div>
          
          </div>
          
        </div>
      </div>
    </section>

    <div class="pagination">
      <ul class="container">
        <li><a href="#" class="btn btn--disabled">&#10094; Prev</a></li>
        <li><a href="#" class="btn btn--sub">01</a></li>
        <li><a href="#" class="btn">02</a></li>
        <li><a href="#" class="btn">03</a></li>
        <li><a href="#" class="btn">04</a></li>
        <li><a href="#" class="btn">05</a></li>
        <li><a href="#" class="btn">06</a></li>
        <li><a href="#" class="btn">07</a></li>
        <li><a href="#" class="btn">08</a></li>
        <li><a href="#" class="btn">09</a></li>
        <li><a href="#" class="btn">10</a></li>
        <li><a href="#" class="btn">Next &#10095;</a></li>
      </ul>
    </div>
  </main>
{% endblock content %}

users/templates/users/user-profile.html
{% extends 'main.html' %}

{% block content %}
<!-- Main Section -->
  <main class="profile my-md">
    <div class="container">
      <div class="layout">
        <div class="column column--1of3">
          <div class="card text-center">
            <div class="card__body dev">
              <img class="avatar avatar--xl" src="{{profile.profile_image.url}}" />
              <h2 class="dev__name">{{profile.name}}</h2>
              <p class="dev__title">{{profile.short_intro}}</p>
              <p class="dev__location">Based in {{profile.location}}</p>
              <ul class="dev__social">
              {% if profile.social_github %}
                <li>
                  <a title="Github" href="{{profile.social_github}}" target="_blank"><i class="im im-github"></i></a>
                </li>
                 {% endif %}
               {% if profile.social_twitter %}
                <li>
                  <a title="Twitter" href="{{profile.social_twitter}}" target="_blank"><i class="im im-twitter"></i></a>
                </li>
                {% endif %}
                {% if profile.social_linkedin %}
                <li>
                  <a title="LinkedIn" href="{{profile.social_linkedin}}" target="_blank"><i class="im im-linkedin"></i></a>
                </li>
                {% endif %}
                {% if profile.social_website %}
                <li>
                  <a title="Personal Website" href="{{profile.social_website}}" target="_blank"><i class="im im-globe"></i></a>
                </li>
                {% endif %}
              </ul>
              <a href="#" class="btn btn--sub btn--lg">Send Message </a>
            </div>
          </div>
        </div>
        <div class="column column--2of3">
          <div class="devInfo">
            <h3 class="devInfo__title">About Me</h3>
            <p class="devInfo__about">
             {{profile.bio}}
            </p>
          </div>
          <div class="devInfo">
            <h3 class="devInfo__title">Skills</h3>
            <div class="devInfo__skills">
            {% for skill in topSkills %}
              <div class="devSkill">
                <h4 class="devSkill__title">{{skill}}</h4>
                <p class="devSkill__info">
                 {{skill.description}}
                </p>
              </div>
              {% endfor %}
              <h3 class="devInfo__subtitle">Other Skills</h3>
              <div class="devInfo__otherSkills">
              {% for skill in otherSkills %}
                <span class="tag tag--pill tag--sub tag--lg">
                  <small>{{skill}}</small>
                </span>
                {% endfor %}
              </div>
            </div>
          </div>
          <div class="devInfo">
            <h3 class="devInfo__title">Projects</h3>
            <div class="grid grid--two">
            {% for project in profile.project_set.all %}
              <div class="column">
                <div class="card project">
                  <a href="{% url 'project' project.id %}" class="project">
                    <img class="project__thumbnail" src="{{project.featured_image.url}}" alt="project thumbnail" />
                    <div class="card__body">
                      <h3 class="project__title">{{project}}</h3>
                      <p><a class="project__author" href="{% url 'user_profile' project.owner.id %}">By {{project.owner.name}}</a></p>
                      <p class="project--rating">
                        <span style="font-weight: bold;">{{project.vote_total}}%</span> Postitive
                        Feedback ({{project.vote_total}} Vote{{project.vote_total|pluralize:"s"}})
                      </p>
                      <div class="project__tags">
                      {% for tag in project.tags.all %}
                        <span class="tag tag--pill tag--main">
                          <small>{{tag}}</small>
                     {% endfor %}
                      </div>
                    </div>
                  </a>
                </div>
              </div>

             {% endfor %}

            </div>
          </div>
        </div>
      </div>
    </div>
  </main>
{% endblock content %}